### ISSUE TITLE
Creating separate repository for releases causes repo history lossage

### ISSUE THREAD

**Issue by rkujawa** [hasherezade/releases#1]
Hello.

Moving releases to a separate repository causes history loss. Anyone interested in the project's history can not track it anymore. It is irrecoverably lost, so please do not do this.

The correct way to do releases would be:
- keep separate repository for every project
- create GitHub release of a given project when needed
- creating release automatically creates a tag that links the given release version to code in repository (so it is possible to check what version of a project corresponds to which tagged source code)
- it can automatically create a source code archive from given repository tag, so you don't have to upload .tar.gz's/zip's with source manually
- you can still upload binaries manually when needed (and link them to a given release version)

In your case clicking the release tags on https://github.com/hasherezade/releases/releases links to an empty repository, with just a single text file.

This is how correctly done per-project release page looks like: https://github.com/rkujawa/9tcfg/releases . Note that tags correctly link to the source code, unlike in your case.

If the idea of creating this "releases" repository was to have a single download point for all your projects, then you could have used GitHub Pages functionality for this instead  - create separate repo for this purpose, then link from there to every project release page that you want visible. https://pages.github.com/

Or, alternatively, host your own simple php/ruby/whatever web page that iterates over GitHub releases API to dynamically construct a list of your released projects:
https://developer.github.com/v3/repos/releases/

Best regards,
rkujawa

**Comment by hasherezade** [comment]
Thanks for the care :) I know how to do it and for my open-source projects I do it in this way:
https://github.com/hasherezade/IAT_patcher/releases
However, I wanted to have a place to host my freeware, non-opensource projects, so I took advantage of this GitHub's feature.
It is intentionally not connected to any code repository.

**Comment by rkujawa** [comment]
Understood. Though I vaguely remember seeing pe-bear sources in a separate repository before, here on GitHub? That's probably where my incorrect assumption came from.

**Comment by hasherezade** [comment]
I guess you mean bearparser (https://github.com/hasherezade/bearparser/) that is a part of PE-bear's code, but not a PE-bear itself (no GUI etc)

**Comment by rkujawa** [comment]
Right, sorry for the noise then 😃 .
